require('mini.surround').setup()
require('mini.pairs').setup()
require('mini.move').setup()
require('mini.cursorword').setup()
require('mini.tabline').setup()
require('mini.comment').setup()
require('mini.pick').setup()
