require('plugins.packer')
require('plugins.lsp')
require('plugins.tree-sitter')
require('plugins.file-explorer')
require('plugins.buffer-line')
require('plugins.status-line')
require('plugins.which-key')
require('plugins.git')
